vkpoll/blueprints/auth.py
import urllib.parse

import requests
from flask import Blueprint, session, request, redirect, abort, flash, url_for

from vkpoll import db
from ..models import User

auth = Blueprint('auth', __name__, url_prefix='/auth')


def get_vk():
    from vkpoll import app
    ans = {
        'id': app.config['VK_API_ID'],
        'secret': app.config['VK_API_SECRET'],
        'url': app.config['VK_API_URL']
    }
    return ans


@auth.route('/testing', methods=['POST'])
def login_testing():
    from vkpoll import app
    if app.config.get('testing'):
        information_about_user = {
            'logged_in': True,
            'id': request.form['user_id'],
            'token': request.form['token'],
            'first_name': request.form['first_name'],
            'last_name': request.form['last_name']
        }
        session.update(information_about_user)
        check_of_user = User.query.filter_by(id=session['id']).all()
        if not check_of_user:
            db.session.add(User(session['id'], session['token']))
        else:
            check_of_user[0].update(session['token'])

    return 'ID: %s' % session.get('id')


@auth.route('/')
def login():
    """ Redirecting to VK to get the code """
    session['previous_url'] = request.referrer

    vk_info = get_vk()
    params = urllib.parse.urlencode(
        {
            'client_id': vk_info['id'],
            'display': 'popup',
            'redirect_uri': vk_info['url'],
            'response_type': 'code',
            'v': 5.73
        }
    )

    url = 'https://oauth.vk.com/authorize?{0}'.format(params)
    return redirect(url)


@auth.route('/get_token')
def get_token():
    if request.args.get('code') is None:
        return abort(501)

    # Get api token
    vk_info = get_vk()
    data = {
        'client_id': vk_info['id'],
        'client_secret': vk_info['secret'],
        'redirect_uri': vk_info['url'],
        'code': request.args.get('code')
    }
    response = requests.post('https://oauth.vk.com/access_token', params=data)

    if response.json().get('access_token') is None:
        abort(501)

    # Check if the user in the database
    check_of_user = User.query.filter_by(
        id=response.json().get('user_id')).first()
    if not check_of_user:
        new_user = User(
            response.json().get('user_id'),
            response.json().get('access_token')
        )
        db.session.add(new_user)
    else:
        check_of_user.update(response.json().get('access_token'))

    db.session.commit()

    # Get information about the user
    data = {
        'user_ids': response.json().get('user_id'),
        'fields': 'bdate',
        'v': 5.73
    }
    url = 'https://api.vk.com/method/users.get'
    response = requests.post(url, params=data).json()
    response = response.get('response')[0]

    information_about_user = {
        'logged_in': True,
        'id': response.get('id'),
        'first_name': response.get('first_name'),
        'last_name': response.get('last_name')
    }
    session.update(information_about_user)
    flash('Welcome! You were logged in', category='success')
    return redirect(session['previous_url'])


@auth.route('/logout')
def logout():
    session.clear()
    flash('You were logged out', category='success')
    return redirect(url_for('index'))

vkpoll/blueprints/poll.py
from functools import wraps
from random import choice
from string import ascii_letters

from flask import Blueprint, session, request, redirect, flash, \
    render_template, url_for, abort

from vkpoll import db
from ..forms import CreatePollForm, DeletePollForm, VotePollForm
from ..models import Poll, Choice, ChoiceUser

poll = Blueprint('poll', __name__)


def is_logged(func):
    """ Processing requests for unauthorized users """

    @wraps(func)
    def wrapper(*args, **kwargs):
        if not session.get('logged_in'):
            flash('You are not authorized!', category='danger')
            return redirect(url_for('index'))
        return func(*args, **kwargs)

    return wrapper


@poll.route('/poll/<url_of_poll>')
def show_poll(url_of_poll):
    current_poll = Poll.query.filter_by(url=url_of_poll).first()
    if not current_poll:
        abort(404)

    options = Choice.query.filter_by(poll_id=current_poll.id).all()

    options_table = [
        {
            'text': option.text,
            'score': len(ChoiceUser.query.filter_by(
                poll_id=current_poll.id,
                choice_id=option.id
            ).all())
        }
        for option in options
    ]

    vote_poll_form = VotePollForm(
        poll_id=current_poll.id,
        poll_url=current_poll.url,
    )

    vote_poll_form.options.choices = [
        (option.id, option.text) for option in options
    ]

    is_user_take_part = ChoiceUser.query.filter_by(
        poll_id=current_poll.id,
        user_id=session.get('id')
    ).all() != []

    return render_template(
        'poll.html',
        poll=current_poll,
        options=options_table,
        DeletePollForm=DeletePollForm(poll_id=current_poll.id),
        VotePollForm=vote_poll_form,
        is_user_take_part=is_user_take_part
    )


@poll.route('/my_polls')
@is_logged
def my_polls():
    polls = Poll.query.filter_by(user_id=session['id']).all()
    return render_template('my_polls.html', polls=polls)


@poll.route('/new', methods=['GET', 'POST'])
@is_logged
def new():
    form = CreatePollForm()
    if request.method == 'POST':
        if not form.validate_on_submit():
            return render_template('add_poll.html', form=form)

        while True:
            url_length = 8
            url_of_poll = ''.join(choice(ascii_letters) for _ in range(
                url_length))

            check_of_poll = Poll.query.filter_by(url=url_of_poll).all()

            if not check_of_poll:
                break

        question = form.title.data
        possible_options = [item for item in form.options.data if item]
        created_poll = Poll(
            url=url_of_poll,
            title=question,
            user_id=session['id']
        )
        db.session.add(created_poll)
        db.session.commit()

        for choice_text in possible_options:
            created_choice = Choice(poll_id=created_poll.id, text=choice_text)
            db.session.add(created_choice)

        db.session.commit()
        flash('Poll successfully created', category='success')
        return redirect(url_for('poll.show_poll', url_of_poll=url_of_poll))
    return render_template('add_poll.html', form=form)


@poll.route('/del', methods=['POST'])
@is_logged
def delete():
    form = DeletePollForm()
    poll_ = Poll.query.filter_by(id=form.poll_id.data).all()
    if not poll_:
        flash('This poll does not exist', category='danger')
    elif poll_[0].user_id == session.get('id'):
        choice_of_users = ChoiceUser.query.filter_by(poll_id=poll_[0].id).all()
        for choice_user in choice_of_users:
            db.session.delete(choice_user)

        options = Choice.query.filter_by(poll_id=poll_[0].id).all()
        for option in options:
            db.session.delete(option)

        db.session.commit()
        db.session.delete(poll_[0])
        db.session.commit()

        flash('Poll successfully deleted', category='success')
    else:
        flash('You do not have the right to remove this poll!',
              category='danger')

    return redirect(url_for('index'))


@poll.route('/make_choice', methods=['POST'])
@is_logged
def make_choice():
    form = VotePollForm()

    check_of_poll = Choice.query.filter_by(
        poll_id=form.poll_id.data,
        id=form.options.data
    ).first()

    if not check_of_poll:
        flash('This poll does not exist', category='danger')
        return redirect(url_for('index'))

    new_choice_user = ChoiceUser(
        poll_id=form.poll_id.data,
        choice_id=form.options.data,
        user_id=session['id']
    )
    db.session.add(new_choice_user)
    db.session.commit()
    return redirect(url_for('poll.show_poll', url_of_poll=form.poll_url.data))

vkpoll/templates/add_poll.html
{% extends 'base.html' %}

{% block title %}VK Poll - Creating poll{% endblock %}
{% block content %}
<section class="mt-5">
    <div class="container">
        <h1 class="display-4 mb-4 font-italic">Creating poll</h1>
        <form action="{{ url_for('poll.new') }}" method="post">
            {{ form.hidden_tag() }}
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Title</label>
                <div class="col-sm-10">
                    {{ form.title(class="form-control", placeholder="Title") }}
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Options</label>
                <div class="col-sm-10 input_fields">
                    <div class="form-group form-row">
                        <div class="col">
                            <input id="options-0" class="form-control" name="options-0" type="text" value="" />
                        </div>
                        <div class="col">
                            <input type="button" id="add_field" class="btn btn-success mb-2" value="Add">
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary mb-2" value="Share">Create</button>
            </div>
        </form>
    </div>
</section>
{% endblock %}

{% block scripts %}
    <script>
        $(function(){

            var number = 1,
            count = 1;

            function add_new_input() {
                if(count < 10){
                    $(".input_fields").append('<div class="form-group form-row"><div class="col"><input class="form-control" name="options-' + number + '" type="text" name="' + name + '" /></div><div class="col"><input type="button" class="remove_field btn btn-danger mb-2" value="delete"></input></div></div>');
                    number++;
                    count++;
                }
                else{
                    console.log("10 ist Max");
                }
            }
            $("#add_field").click(add_new_input);
            $("body").on("click",".remove_field",function(){
                $(this).parent().parent().remove();
                count--;
            });
        });
    </script>
{% endblock%}

vkpoll/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'style.css') }}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<section class="mt-4">
    <div class="container">
        <div class="col-lg-6 mx-auto">
            <header>
                <h1 class="display-4">
                    VK Poll
                </h1>
            </header>

            <div class="mt-4">
                <ul class="nav justify-content-center">
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('index') }}">Home</a>
                    </li>
                    {% if session.get('logged_in') %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('poll.new') }}">Create poll</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">Log out</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">Log in</a>
                    </li>
                    {% endif %}
                </ul>
            </div>

            <div class="mt-4">
            {% block content %}{% endblock %}
            </div>

            <div class="footer">
                <footer class="footer text-center">
                    <div class="container">
                    <p class="text-muted small mb-0">Copyright © Andrey Varfolomeev 2018</p>
                    </div>
                </footer>
            </div>
        </div>
    </div>
</section>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js"></script>
    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.21.0/moment.js"></script>
    {% block scripts %}{% endblock %}
</body>
</html>

vkpoll/templates/index.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename = 'style.css') }}">

    <title>VK Poll</title>
</head>
<body>
    <!-- Header -->
    <header class="header">
        <div class="container text-center">
            <h1 class="mb-1">VK Poll</h1>
            <h3 class="mb-5"><em>Web application for creating private polls.</em></h3>
            <a class="btn btn-primary btn-xl" href="{{ url_for('auth.login') }}"><i class="fa fa-sign-in"></i> Login with VK</a>
        </div>
    </header>

    <section class="content-section" id="about">
        <div class="container text-center">
            <div class="row">
                <div class="col-lg-6 mx-auto">
                    <h2>Create Poll!</h2>
                    <p class="lead mb-5">Create simple poll in order to know the opinions of people</p>
                </div>
                <div class="col-lg-6 mx-auto">
                    <h2>Share!</h2>
                    <p class="lead mb-5">Each poll creates a private link. Share it in the dialogs!</p>
                </div>
            </div>
        </div>
    </section>

    <section class="content-section bg-primary text-white">
        <div class="container text-center">
            <h2 class="mb-4">Open Source</h2>
            <p class="lead mb-5">The application is part of Open Source. This means that you can participate in the development.</p>
            <a href="https://github.com/andreyvpng/vkpoll" class="btn btn-xl btn-light mr-4"><i class="fa fa-github"></i> Github</a>
            <a href="https://t.me/andreyvpng" class="btn btn-xl btn-dark"><i class="fa fa-users"></i> Suggest</a>
        </div>
    </section>

    <!-- Footer -->
    <footer class="footer text-center">
        <div class="container">
            <p class="text-muted small mb-0">Copyright &copy; Andrey Varfolomeev 2018</p>
        </div>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

vkpoll/templates/my_polls.html
{% extends 'base.html' %}

{% block title %}VK Poll - My polls{% endblock %}
{% block content %}
<section class="mt-5">
    <div class="container">
        <h1 class="display-4 mb-4 font-italic">My polls</h1>
        {% for poll in polls %}
        <div class="poll">
            <h4 class="display-6 font-italic">
                <a href="{{ url_for('poll.show_poll', url_of_poll=poll.url) }}">
                    {{ poll.title }}
                </a>
            </h4>
        </div>
        {% else %}
        <div class="text-center">
            <h5>There's nothing here. Maybe it's time to create a poll? :)</h5>
        </div>
        {% endfor %}
    </div>
</section>
{% endblock %}

vkpoll/templates/nav.html
<div class="container mt-5">
    <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
        <header class="masthead mb-auto">
            <div class="inner">
                <h3 class="masthead-brand">VK Poll</h3>
                <nav class="nav nav-masthead justify-content-center">
                    <a class="nav-link active" href="{{ url_for('index') }}">Home</a>
                    {% if session.get('logged_in') %}
                    <a class="nav-link" href="{{ url_for('poll.new') }}">Create a Poll</a>
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                    {% else %}
                    <a class="nav-link" href="{{ url_for('auth.login') }}">Login with VK</a>
                    {% endif %}
                </nav>
            </div>
        </header>
    </div>
</div>

vkpoll/templates/poll.html
{% extends 'base.html' %}

{% block title %}VK Poll - {{ poll.title }}{% endblock %}
{% block content %}

<h3>What is your favourite language?</h3>
<div class="mt-4 mb-4 media">
    <img id="image_of_user" class="align-self-start mr-3" src="">
    <div class="media-body">
        <a href="https://vk.com/id{{ poll.user_id }}"><h6 id="name_of_user" class="mt-0"></h6></a>
        <p><time class="updated" itemprop="dateModified" datetime="{{ poll.pub_date }}"></time></p>
    </div>
</div>
{% if poll.user_id == session['id'] %}
<form class="d-inline" method='POST' action="{{ url_for('poll.delete') }}">
    {{ DeletePollForm.poll_id }}
    {{ DeletePollForm.submit(class="btn btx-1 btn-primary mb-2") }}
</form>
{% endif %}
<input class="d-inline btn btn-primary mb-2 clipboard" type="button" data-clipboard-text="{{ request.base_url }}" value="Copy a link" />
{% if not ((session.get('logged_in') and not is_user_take_part) or (not session.get('logged_in') and is_user_take_part)) %}

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Option</th>
                <th scope="col">Score</th>
            </tr>
        </thead>
        <tbody>
        {% for option in options %}
            <tr>
                <td>{{ option['text'] }}</td>
                <td>{{ option['score'] }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% else %}
    <form action="{{ url_for('poll.make_choice') }}" method="post">
        {{ VotePollForm.poll_id }}
        {{ VotePollForm.poll_url }}
        <div class="form-group">
            <div class="row">
                <legend class="col-form-label col-3 pt-0">Options</legend>
                <div class="col-9">
                    <ul id="options" class="list-inline">
                    {% for option in VotePollForm.options %}
                        <li>
                            <div class="form-check form-check-inline">
                                {{ option(class="form-check-input") }}
                                <label class="form-check-label">{{ option.label }}</label>
                            </div>
                        </li>
                    {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        {{ VotePollForm.submit(class="btn btn-primary") }}
    </form>
{% endif %}
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        new ClipboardJS('.btn');

        var user_id = {{ poll.user_id }}
        var req="https://api.vk.com/method/users.get?user_ids=" + user_id + "&fields=photo_50&v=5.73"
        $(document).ready(function() {
            $.ajax({
                url: req,
                dataType: "jsonp",
                success: function(e){
                    var first_name = e.response[0].first_name;
                    $('#image_of_user').attr('src', e.response[0]["photo_50"]);
                    $('#name_of_user').text(e.response[0]["first_name"] + ' ' + e.response[0]["last_name"]);
                    console.log(e.response[0]["photo_50"])
                }
            });
        });

        var now = moment();
        $('time').each(function(i, e) {
            var time = moment($(e).attr('datetime'));
            if(now.diff(time, 'days') <= 1) {
                $(e).html('<span>' + moment(time).format('LLL') + '</span>');
            }
        });
    </script>
{% endblock %}

vkpoll/templates/stat.html
{% extends 'base.html' %}

{% block title %}VK Poll - My polls{% endblock %}
{% block content %}
{% include 'nav.html' %}
<section class="mt-5">
    <div class="container">
        <h1>Statistics</h1>
        <table class="table">
            <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Count</th>
                </tr>
            </thead>
            <tbody>
            {% for elem, value in stat.items()%}
            <tr>
                <th scope="row">1</th>
                <td>{{ elem }}</td>
                <td>{{ value }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</section>
{% endblock %}