app/auth.py
import requests
import urllib
from flask import Blueprint, request, abort, redirect, url_for, session
from db_helper import create_new_user, update_token_of_user, get_user

auth = Blueprint('auth', __name__)


def get_vk():
	from main import app
	ans = {
		'id': app.config['VK_API_ID'],
		'secret': app.config['VK_API_SECRET'],
		'url': app.config['VK_API_URL']
	}
	return ans


@auth.route('/redirect_to_vk_login', methods=['POST', 'GET'])
def vk_login():
	session['previous_url'] = request.referrer

	vk_info = get_vk()
	params = urllib.parse.urlencode(
		{
			'client_id': vk_info['id'],
			'display': 'popup',
			'redirect_uri': vk_info['url'],
			'response_type': 'code',
			'v': 5.73
		}
	)
	url = 'https://oauth.vk.com/authorize?%s' % params
	return redirect(url)


@auth.route('/login')
def login():
	if request.args.get('code') is None:
		return abort(501)

	# Get api token
	vk_info = get_vk()
	data = {
		'client_id': vk_info['id'],
		'client_secret': vk_info['secret'],
		'redirect_uri': vk_info['url'],
		'code': request.args.get('code')
	}
	response = requests.post('https://oauth.vk.com/access_token', params=data)

	if response.json().get('access_token') is None:
		abort(501)

	# Check if the user in the database
	check_of_user = get_user(response.json().get('user_id'))
	if not check_of_user:
		create_new_user(response.json().get('user_id'), response.json().get('access_token'))
	else:
		update_token_of_user(response.json().get('access_token'), response.json().get('user_id'))

	# Get information about the user
	data = {
		'user_ids': response.json().get('user_id'),
		'fields': 'bdate',
		'v': 5.73
	}
	url = 'https://api.vk.com/method/users.get'
	response = requests.post(url, params=data).json()
	response = response.get('response')[0]

	information_about_user = {
		'logged_in': True,
		'user_id': response.get('id'),
		'first_name': response.get('first_name'),
		'last_name': response.get('last_name')
	}
	session.update(information_about_user)
	return redirect(session['previous_url'])


@auth.route('/logout')
def logout():
	session.pop('logged_in', None)
	return redirect(url_for('main.index'))

app/blueprints/auth.py
import urllib.parse

import requests
from flask import Blueprint, request, abort, redirect, url_for, session, flash

from app import app, database

auth = Blueprint('auth', __name__)


def get_vk():
    from main import app
    ans = {
        'id': app.config['VK_API_ID'],
        'secret': app.config['VK_API_SECRET'],
        'url': app.config['VK_API_URL']
    }
    return ans


@auth.route('/testing', methods=['POST'])
def auth_for_testing():
    """ Authorization, which is only used for testing! """
    if app.config.get('TESTING'):
        information_about_user = {
            'logged_in': True,
            'user_id': request.form['user_id'],
            'token': request.form['token'],
            'first_name': request.form['first_name'],
            'last_name': request.form['last_name']
        }
        session.update(information_about_user)
        check_of_user = database.get_user(session['user_id'])
        if not check_of_user:
            database.create_new_user(session['user_id'], session['token'])
        else:
            database.update_token_of_user(session['user_id'], session['token'])

    return redirect(url_for('main.index'))


@auth.route('/redirect_to_vk_login', methods=['POST', 'GET'])
def vk_login():
    """ Redirecting to VK to get the code """
    session['previous_url'] = request.referrer

    vk_info = get_vk()
    params = urllib.parse.urlencode(
        {
            'client_id': vk_info['id'],
            'display': 'popup',
            'redirect_uri': vk_info['url'],
            'response_type': 'code',
            'v': 5.73
        }
    )

    url = 'https://oauth.vk.com/authorize?%s' % params
    return redirect(url)


@auth.route('/login')
def login():
    if request.args.get('code') is None:
        return abort(501)

    # Get api token
    vk_info = get_vk()
    data = {
        'client_id': vk_info['id'],
        'client_secret': vk_info['secret'],
        'redirect_uri': vk_info['url'],
        'code': request.args.get('code')
    }
    response = requests.post('https://oauth.vk.com/access_token', params=data)

    if response.json().get('access_token') is None:
        abort(501)

    # Check if the user in the database
    check_of_user = database.get_user(response.json().get('user_id'))
    if not check_of_user:
        database.create_new_user(
            response.json().get('user_id'),
            response.json().get('access_token')
        )
    else:
        database.update_token_of_user(
            response.json().get('access_token'),
            response.json().get('user_id')
        )

    # Get information about the user
    data = {
        'user_ids': response.json().get('user_id'),
        'fields': 'bdate',
        'v': 5.73
    }
    url = 'https://api.vk.com/method/users.get'
    response = requests.post(url, params=data).json()
    response = response.get('response')[0]

    information_about_user = {
        'logged_in': True,
        'user_id': response.get('id'),
        'first_name': response.get('first_name'),
        'last_name': response.get('last_name')
    }
    session.update(information_about_user)
    flash('Welcome! You were logged in', category='success')
    return redirect(session['previous_url'])


@auth.route('/logout')
def logout():
    session.clear()
    flash('You were logged out', category='success')
    return redirect(url_for('main.index'))

app/main.py
from random import choice
from string import ascii_letters
from functools import wraps
from flask import Blueprint, redirect, render_template, session, abort, request, url_for, flash
from db_helper import get_polls_of_user, get_poll_via_url, get_poll_via_id, get_possible_choice, create_new_poll, \
	create_choice, is_user_take_part, delete_poll, is_url_available

main = Blueprint('main', __name__)


def is_logged(func):
	@wraps(func)
	def wrapper(*args, **kwargs):
		if not session.get('logged_in'):
			flash('Ты не авторизирован!')
			return redirect(url_for('main.index'))
		return func(*args, **kwargs)
	return wrapper


@main.route('/')
def index():
	polls = None
	if session.get('logged_in'):
		polls = get_polls_of_user(session.get('user_id'))
	return render_template('index.html', polls=polls)


@main.route('/add_poll', methods=['GET', 'POST'])
@is_logged
def add_poll():
	if request.method == "POST":
		while True:
			url_of_poll = ''.join(choice(ascii_letters) for _ in range(30))
			if is_url_available(url_of_poll):
				break
		choices = request.form.getlist('choice')
		create_new_poll(url_of_poll, session['user_id'], request.form['title'], choices)
		return redirect(url_for('main.show_poll', url_of_poll=url_of_poll))
	return render_template('add_poll.html')


@main.route('/del_poll_<poll_id>', methods=['POST'])
@is_logged
def dell_poll(poll_id):
	poll = get_poll_via_id(poll_id)
	if poll.get('user_id') == session.get('user_id'):
		delete_poll(poll_id)
	else:
		flash('У тебя нет прав на удаление этого опроса!')
	return redirect(url_for('main.index'))


@main.route('/poll_<url_of_poll>')
def show_poll(url_of_poll):
	poll = get_poll_via_url(url_of_poll)
	if not poll:
		abort(404)

	options = get_possible_choice(poll['id'])
	user_choice = is_user_take_part(session['user_id'], options)
	return render_template('poll.html', poll=poll, options=options, user_choice=user_choice)


@main.route('/make_choice', methods=['POST'])
@is_logged
def make_choice():
	poll_id = request.form.get('poll_id')
	choice_id = request.form.get('choice_id')

	options = get_possible_choice(poll_id)
	user_choice = is_user_take_part(session['user_id'], options)

	if not user_choice['answered']:
		create_choice(session['user_id'], poll_id, choice_id)
	return redirect(url_for('main.show_poll', url_of_poll=request.form.get('poll_url')))

app/templates/add_poll.html
{% extends 'base.html' %}

{% block title %}VK Poll - Creating poll{% endblock %}
{% block content %}
{% include 'nav.html' %}
<section class="mt-5">
    <div class="container">
        <div class="jumbotron">
            <h1 class="display-4 font-italic">Creating poll</h1>
        </div>
        <form action="{{ url_for('main.add_poll') }}" method="post">
            <div class="form-group row">
                <label for="colFormLabel" class="col-sm-2 col-form-label">Title</label>
                <div class="col-sm-10">
                  <input class="form-control" id="colFormLabel" name="title" placeholder="Title">
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Options</label>
                <div class="col-sm-10 input_fields">
                    <div class="form-group form-row">
                        <div class="col">
                            <input class="form-control" name="choice">
                        </div>
                        <div class="col">
                            <input type="button" id="add_field" class="btn btn-success mb-2" value="Add"></input>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary mb-2" value="Share">Create</button>
            </div>
        </form>
    </div>
</section>
{% endblock %}

{% block scripts %}
    <script>
        $(function(){

            var number = 1;

            $("#add_field").click(function(){
                if(number < 11){
                    var name = "input";
                    name = name + number;
                    $(".input_fields").append('<div class="form-group form-row"><div class="col"><input class="form-control" name="choice" type="text" name="' + name + '" /></div><div class="col"><input type="button" class="remove_field btn btn-danger mb-2" value="delete"></input></div></div>');
                    number++;
                }
                else{
                    console.log("10 ist Max");
                }
            });
            $("body").on("click",".remove_field",function(){
                $(this).parent().parent().remove();
                number--;
            });
        });
    </script>
{% endblock%}

app/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }} fade show">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <strong>Info!</strong> {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    {% block content %}
    {% endblock %}

    <div class="container mt-5 footer">
        <div class="row">
            <div class="col-6">
                <h6>Andrey Varfolomeev© 2018</h6></div>
            <div class="col-6 social-icons">
                <a href="https://github.com/andreyvpng/vkpoll">
                    GitHub
                </a>
                <a href="{{ url_for('stat.show_stat') }}">
                    Statistics
                </a>
            </div>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.21.0/moment.js"></script>
    <!-- Clipboard -->
    <script src="https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js"></script>
    {% block scripts %}
    {% endblock %}
</body>
</html>

app/templates/my_polls.html
{% extends 'base.html' %}

{% block title %}VK Poll - My polls{% endblock %}
{% block content %}
{% include 'nav.html' %}
<section class="mt-5">
    <div class="container">
        <div class="jumbotron">
            <h1 class="display-4 font-italic">My polls</h1>
        </div>
        {% for poll in polls %}
        <div class="poll">
            <h1 class="display-6 font-italic">
                <a href="{{ url_for('main.show_poll', url_of_poll=poll.url) }}">
                    {{ poll.question }}
                </a>
            </h1>
        </div>
        {% else %}
        <div class="text-center">
            <h1 class="display-4">There's nothing here. Maybe it's time to create a poll? :)</h1>
        </div>
        {% endfor %}
    </div>
</section>
{% endblock %}

app/templates/nav.html
<div class="container mt-5">
    <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
        <header class="masthead mb-auto">
            <div class="inner">
                <h3 class="masthead-brand">VK Poll</h3>
                <nav class="nav nav-masthead justify-content-center">
                    <a class="nav-link active" href="{{ url_for('main.index') }}">Home</a>
                    {% if session.get('logged_in') %}
                    <a class="nav-link" href="{{ url_for('main.add_poll') }}">Create a Poll</a>
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                    {% else %}
                    <a class="nav-link" href="{{ url_for('auth.vk_login') }}">Login with VK</a>
                    {% endif %}
                </nav>
            </div>
        </header>
    </div>
</div>